name: Check Code Style and Unit Tests
on: [push]
jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        php-versions: ['7.4', '8.0']
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer
      - name: Composer
        run: composer install --prefer-dist
      - name: Check Code Style
        run: ./vendor/bin/phpcs src -v --standard=PSR2
      - name: Unit Tests
        run: ./vendor/bin/phpunit --coverage-text --colors
